services:
  #nginx
  scserver:
    container_name: scserver
    image: nginx:stable-alpine
    restart: always
    ports:
      - "6084:80"
    volumes:
      - ../html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - scorpionet

  #php
  scapi:
    container_name: scapi
    build:
      context: .
      dockerfile: ./php/Dockerfile
    restart: always
    volumes:
      - ../html:/var/www/html
    networks:
      - scorpionet

  #db
  scdb:
    container_name: scdb
    platform: linux/x86_64
    image: mysql:8
    ports:
      - 6086:3306
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - scdata:/var/lib/mysql
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_DATABASE: scorpio
      MYSQL_ROOT_PASSWORD: r00tadmin
    networks:
      - scorpionet

  #phpadmin
  scadmin:
    container_name: scadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: scdb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 6088:80
    networks:
      - scorpionet

volumes:
  scdata:
    driver: local
    name: scdata

networks:
  scorpionet:
    name: scorpionet
